### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by razorsyntax** [mhtghn/nativescript-ui-highcharts#1]
Do you know if anyone has performed any actual tests to determine how much slower this is to the native charts?  If it's negligible then this might be great to use for customization.

**Comment by mhtghn** [comment]
Hi @razorsyntax , I didn't performed the test. So for now I cannot tell you if its negligible or not.
But Ive been using this plugin in some of my apps and it's not really slow (surprisingly pretty fast), its just that compared to native solution it _SHOULD_ be slower.
The disclaimer is for those who are really focused on the performance of their apps, of course if you want the many customization possibility of Highcharts you can use this

**Comment by razorsyntax** [comment]
@mhtghn Thank you for the answer!  I love the flexibility offered by Highcharts.  I'll definitely try it out!  I wish the Nativescript charts had more flexibility and options as far as styling goes.  This should do the trick!

Thanks again!
