### ISSUE TITLE
Horizontal xAxis scroll

### ISSUE THREAD

**Issue by mrcretu** [mhtghn/nativescript-ui-highcharts#10]
Hello, after a lot of research I still can't find a working solution for a horizontal xAxis scroll. Maybe I don't know exactly how to accomplish that and someone can help me here.
Example for what I want: https://jsfiddle.net/BhavyaAprajita/zja90wf2/1/

I'm currently develop an app with nativescript + angular.

Thanks in advance

**Comment by mhtghn** [comment]
Dont know if you already found out but this feature is only available in HighStocks (you can see in the example you linked, the imports lines). And this plugin is for now only compatible with Highcharts and others modules related to Highcharts.
