### ISSUE TITLE
please migrate the plugin to NS7 and Angular 10

### ISSUE THREAD

**Issue by cjohn001** [mhtghn/nativescript-ui-highcharts#17]

**Comment by mhtghn** [comment]
Hello @cjohn001 
Sorry for the wait. I had to wrap my head around the new plugin seed workspace and fix some issues before publishing.

Anyway the NS 7 and Angular 10 version of this plugin is accessible from here [https://github.com/mhtghn/ns-plugins/tree/master/packages/nativescript-highcharts](https://github.com/mhtghn/ns-plugins/tree/master/packages/nativescript-highcharts)

**Comment by cjohn001** [comment]
> Hello @cjohn001
> Sorry for the wait. I had to wrap my head around the new plugin seed workspace and fix some issues before publishing.
> 
> Anyway the NS 7 and Angular 10 version of this plugin is accessible from here https://github.com/mhtghn/ns-plugins/tree/master/packages/nativescript-highcharts

@mhtghn : Thank you very much!
