### ISSUE TITLE
Can you add more highcharts modules ?

### ISSUE THREAD

**Issue by lehongwang** [mhtghn/nativescript-ui-highcharts#6]
Can you add more modules such as 
https://code.highcharts.com/modules/organization.js

or is there a way to import external module JS

thank you

**Comment by mhtghn** [comment]
Hi @lehongwang 

In the 1.2.0 version Ive added the sankey and organization modules, for now I dont have much time to make it use external JS module. I added them manually.

Thank you for your feedback.
